import { BookOpen, Brain, Timer, Users } from "lucide-react";
import { ISkill } from "../Interfaces/skills";
import {
  BootstrapIcon,
  CIcon,
  CssIcon,
  ExpressIcon,
  FigmaIcon,
  FramerIcon,
  GitIcon,
  HtmlIcon,
  JavaIcon,
  JQueryIcon,
  JsIcon,
  MongoIcon,
  NextIcon,
  NodeIcon,
  PostManIcon,
  PythonIcon,
  ReactIcon,
  ReduxIcon,
  SqlIcon,
  SupabaseIcon,
  TailwindIcon,
  TsIcon,
} from "../icons/index";
export const skills: ISkill[] = [
  { name: "HTML5", category: "Frontend", icon: <HtmlIcon /> },
  { name: "CSS", category: "Frontend", icon: <CssIcon /> },
  { name: "BootStrap", category: "Frontend", icon: <BootstrapIcon /> },
  { name: "TailwindCSS", category: "Frontend", icon: <TailwindIcon /> },
  { name: "JavaScript", category: "Programming Languages", icon: <JsIcon /> },
  { name: "TypeScript", category: "Programming Languages", icon: <TsIcon /> },
  { name: "JQuery", category: "Frontend", icon: <JQueryIcon /> },
  { name: "React.js", category: "Frontend", icon: <ReactIcon /> },
  { name: "Redux", category: "Frontend", icon: <ReduxIcon /> },
  { name: "Framer Motion", category: "Frontend", icon: <FramerIcon /> },
  { name: "Next.js", category: "Frontend", icon: <NextIcon /> },
  { name: "Node.js", category: "Backend", icon: <NodeIcon /> },
  { name: "Supabase", category: "Backend", icon: <SupabaseIcon /> },
  { name: "GitHub", category: "Tools", icon: <GitIcon /> },
  { name: "Express.js", category: "Backend", icon: <ExpressIcon /> },
  { name: "MySQL", category: "Backend", icon: <SqlIcon /> },
  { name: "MongoDB", category: "Backend", icon: <MongoIcon /> },
  { name: "C++", category: "Programming Languages", icon: <CIcon /> },
  { name: "Python", category: "Programming Languages", icon: <PythonIcon /> },
  { name: "Java", category: "Programming Languages", icon: <JavaIcon /> },
  { name: "Post Man", category: "Tools", icon: <PostManIcon /> },
  { name: "Figma", category: "Tools", icon: <FigmaIcon /> },
  {
    name: "Team Communication",
    category: "Soft Skills",
    icon: <Users className="w-6 h-6 text-main" aria-label="Users icon" />,
  },
  {
    name: "Problem Solving",
    category: "Soft Skills",
    icon: <Brain className="w-6 h-6 text-main" aria-label="Brain icon" />,
  },
  {
    name: "Project Planning",
    category: "Soft Skills",
    icon: <BookOpen className="w-6 h-6 text-main" aria-label="BookOpen icon" />,
  },
  {
    name: "Time Management",
    category: "Soft Skills",
    icon: <Timer className="w-6 h-6 text-main" aria-label="Timer icon" />,
  },
];
// categories
export const skillsCategory: string[] = [
  "All Skills",
  "Frontend",
  "Backend",
  "Programming Languages",
  "Tools",
  "Soft Skills",
];
